### ISSUE TITLE
 file=logger/setup.go:44 level=fatal request logger setup error: %s0x4844520

### ISSUE THREAD

**Issue by bingoku** [go-admin-team/go-admin#290]
版本：master 最新
运行的配置 settings.sqlite.yml

```
settings:
  application:
    # dev开发环境 test测试环境 prod线上环境
    mode: dev
    # 服务器ip，默认使用 0.0.0.0
    host: 0.0.0.0
    # 服务名称
    name: testApp
    # 端口号
    port: 8000 # 服务端口号
    readtimeout: 1
    writertimeout: 2
    # 数据权限功能开关
    enabledp: false
  logger:
    # 日志存放路径
    path: /var/tmp/logs
    # 控制台日志
    stdout: true
    # 日志等级
    level: Debug
    # 业务日志开关
    enabledbus: true
    # 请求日志开关
    enabledreq: false
    # 数据库日志开关 dev模式，将自动开启
    enableddb: false
    # 自动任务日志开关 dev模式，将自动开启
    enabledjob: false
  jwt:
    # token 密钥，生产环境时及的修改
    secret: go-admin
    # token 过期时间 单位：秒
    timeout: 3600
  database:
    # 数据库类型 mysql，sqlite3， postgres
    driver: sqlite3
    # 数据库连接sqlite3数据文件的路径
    source: sqlite3.db
  gen:
    # 代码生成读取的数据库名称
    dbname: dbname
    # 代码生成是使用前端代码存放位置，需要指定到src文件夹，相对路径
    frontpath: ../go-admin-ui/src
  ssl: false

```
# 运行会报错。
```
❯ ./go-admin migrate -c=config/settings.sqlite.yml
start init
warning config not found settings.ssl in the configuration
2020-11-09 11:23:42  file=logger/setup.go:44 level=fatal request logger setup error: %s0x4844520
```
